image:
  repository: "fluent/fluentd-kubernetes-daemonset"
  tag: "v1.13-debian-gcs-arm64-1"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi
env:
- name: FLUENT_ELASTICSEARCH_HOST
  value: "elasticsearch-master.default.svc.cluster.local"
- name: FLUENT_ELASTICSEARCH_PORT
  value: "9200"
- name: FLUENT_ELASTICSEARCH_USER
  valueFrom:
    secretKeyRef:
      name: elastic-credentials
      key: username
- name: FLUENT_ELASTICSEARCH_PASSWORD
  valueFrom:
    secretKeyRef:
      name: elastic-credentials
      key: password
metrics:
  serviceMonitor:
    enabled: false

readinessProbe:
  httpGet:
    path: /metrics
    port: metrics
  initialDelaySeconds: 100
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 5
