apiVersion: v1
kind: Service
metadata:
  name: kibana-nodeport
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 31005
    nodePort: 30005
    targetPort: 5601
    name: http
    protocol: TCP
  selector:
    app: kibana
    release: kibana
