prometheusOperator:
  admissionWebhooks:
    enabled: false
  tlsProxy:
    enabled: false

prometheus:  
  prometheusSpec:
    ## How long to retain metrics
    ##
    retention: 10d

    ## Maximum size of metrics
    ##
    retentionSize: ""
    resources: {}
    # requests:
    #   memory: 400Mi

    ## The remote_read spec configuration for Prometheus.
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#remotereadspec
    remoteRead: 
      - url: "http://influxdb.default.svc.cluster.local:8086/api/v1/prom/read?db=prometheus"

    ## The remote_write spec configuration for Prometheus.
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#remotewritespec
    remoteWrite: 
      - url: "http://influxdb.default.svc.cluster.local:8086/api/v1/prom/write?db=prometheus"

    ## Prometheus StorageSpec for persistent data
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/storage.md
    ##
    storageSpec: {}
    #   volumeClaimTemplate:
    #     spec:
    #       storageClassName: local-storage
    #       accessModes: ["ReadWriteOnce"]
    #       resources:
    #         requests:
    #           storage: 50Gi
    #     selector: {}

    grafana:
      enabled: true
      namespaceOverride: ""
    
      ## Deploy default dashboards.
      ##
      defaultDashboardsEnabled: true
    
      adminPassword: prom-operator
    
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
    
          ## Annotations for Grafana dashboard configmaps
          ##
          annotations: {}
        datasources:
          enabled: true
          defaultDatasourceEnabled: true
      additionalDataSources: 
        - name: influxdb
          type: influxdb
          access: server
          url: http://influxdb.default.svc.cluster.local:8086
          # basicAuth: true
          # basicAuthPassword: pass
          # basicAuthUser: daco
          editable: true
          jsonData:
              tlsSkipVerify: true
    