apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 31002
    nodePort: 30002
    targetPort: 9090
    name: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: kube-prometheus-stack-prometheus
