apiVersion: v1
kind: PersistentVolume
metadata:
  name: memory-alpha
spec:
  capacity:
    storage: 50G 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /media/cargobay/memory-alpha
    server: 192.168.2.50 
  persistentVolumeReclaimPolicy: Retain