apiVersion: v1
kind: PersistentVolume
metadata:
  name: memory-alpha
spec:
  capacity:
    storage: 50G
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /media/cargobay/memory-alpha
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - starfleet
