apiVersion: v1
kind: PersistentVolume
metadata:
  name: memory-delta
spec:
  capacity:
    storage: 30G 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /media/cargobay/memory-delta
    server: 192.168.2.50 
  persistentVolumeReclaimPolicy: Retain
