apiVersion: v1
kind: Service
metadata:
  name: influxdb-nodeport
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 31004
    nodePort: 30004
    targetPort: 8086
    name: http
    protocol: TCP
  selector:
    app.kubernetes.io/instance: influxdb
    app.kubernetes.io/name: influxdb
